language: python
python:
  - "2.7"
install:
  - python setup.py develop
  - pip install coverage
script:
  - coverage run setup.py test
  - coverage report -m striketracker/*.py striketracker/tests/*.py